const CITIES_DB = [
    "Agra", "Ahmedabad", "Ajmer", "Aligarh", "Allahabad", "Amritsar", "Aurangabad", 
    "Bangalore", "Bareilly", "Belgaum", "Bhilai", "Bhiwandi", "Bhopal", "Bhubaneswar", "Bikaner", "Bokaro",
    "Calicut", "Chandigarh", "Chennai", "Coimbatore", "Cuttack",
    "Darjeeling", "Dehradun", "Delhi", "Dhanbad", "Dharwad", "Durgapur",
    "Erode", "Ernakulam", "Etawah",
    "Faridabad", "Firozabad",
    "Gandhinagar", "Gangtok", "Gaya", "Ghaziabad", "Goa", "Gorakhpur", "Gulbarga", "Guntur", "Gurgaon", "Guwahati", "Gwalior",
    "Haldwani", "Hampi", "Haridwar", "Hubli", "Hyderabad",
    "Imphal", "Indore", "Itanagar",
    "Jabalpur", "Jaipur", "Jalandhar", "Jalgaon", "Jammu", "Jamnagar", "Jamshedpur", "Jhansi", "Jodhpur",
    "Kakinada", "Kalyan", "Kanpur", "Kanyakumari", "Kochi", "Kolhapur", "Kolkata", "Kollam", "Kota", "Kozhikode", "Kurnool",
    "Lucknow", "Ludhiana",
    "Madurai", "Malegaon", "Manali", "Mangalore", "Mathura", "Meerut", "Moradabad", "Mumbai", "Muzaffarnagar", "Mysore",
    "Nagpur", "Nanded", "Nashik", "Nellore", "Noida",
    "Ooty", 
    "Panaji", "Panipat", "Patiala", "Patna", "Pondicherry", "Pune", "Puri",
    "Raipur", "Rajahmundry", "Rajkot", "Rampur", "Ranchi", "Rishikesh", "Roorkee", "Rourkela",
    "Saharanpur", "Salem", "Shimla", "Shillong", "Siliguri", "Solapur", "Srinagar", "Surat",
    "Thane", "Thanjavur", "Thiruvananthapuram", "Thrissur", "Tiruchirappalli", "Tirunelveli", "Tirupati", "Tiruppur",
    "Udaipur", "Ujjain",
    "Vadodara", "Varanasi", "Vasai", "Vellore", "Vijayawada", "Visakhapatnam",
    "Warangal"
];
